### ISSUE TITLE
This is not your issue by mine. ;-)

### ISSUE THREAD

**Issue by dlevitryon** [HardRainbow/CNC_gcode-to-reprap-converter#2]
I am having a hard time getting your .py to run. I am new to python and have really never use it must. Could you give quick step to step from the download to run stage. I have been trying to use windows power shell to run your script, and also Python it self. It just seems to open and close really fast. I have to me missing something super easy! 

Any help would be awesome! Thanks! I am trying to get a Pinewood derby car up and going lol

**Comment by VirToReal** [comment]
Sorry for the late response, i did not expect that someone really (want to) use my script ;-)

It has no graphical interface, you have to run it via terminal. I realy don't know how this works with Windows, in Linux you just have to type python gcode_converterV03.1.py and it will tell you in the Terminal how to use it. 

For example: python gcode_converterV03.1.py 1200 150 1200 pycam_gcode_file1.gcode [pycam_gcode_file2.gcode ... ]

After that the Script will convert your pycam/heekscnc g-code File into a "*_converted.gcode" one which your 3D-Printer will now correctly interpret. 

Maybe there is something like a Python Terminal in Windows where you can run this script. Sorry, can't give you more information on that :(

**Comment by dlevitryon** [comment]
LOL I got it working! I got it to work in CMD promt! Thanks for the help. I did a little CNC from the converter and it seems spot on. Thanks again!

**Comment by VirToReal** [comment]
Good to hear :)
