### ISSUE TITLE
Question: Does this work with CNC G-Code generated by easel 

### ISSUE THREAD

**Issue by TGC-TECH** [HardRainbow/CNC_gcode-to-reprap-converter#3]
Sorry for creating an issue with this but I could not find a way to email you directly... I know  you have probably never tested this but in theory, this should work because both PyCam and easel generate G-Code meant for GRBL, once I finally start working on my CNC I would be happy to test it, however, I just figured I would ask to make sure I was not overlooking something obvious. 
Thanks!

**Comment by VirToReal** [comment]
Yeah, don't worry about that. If there are any difficulties, give me a notice and I'll go check
